/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kkp.sipenalek.project;

import com.kkp.sipenalek.ComboBoxItem;
import com.kkp.sipenalek.DBConnection;
import com.kkp.sipenalek.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.HashMap;

/**
 *
 * @author Dell
 */
public class ProjectRevision extends javax.swing.JFrame {

    /**
     * Creates new form ProjectCreate
     */
    public ProjectRevision(int projectId) {

        this.name = UserSession.emp_name;
        this.nik = UserSession.nik;
        this.role = UserSession.role;
        this.pos = UserSession.pos;
        
        this.projectId = projectId;
        initComponents();
        
        DBConnection DB = new DBConnection();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        try {
            populateComboBox();
            display();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pNumberInp = new javax.swing.JTextField();
        pNameInp = new javax.swing.JTextField();
        pDateInp = new javax.swing.JTextField();
        noteInp = new javax.swing.JTextField();
        commentInp = new javax.swing.JTextField();
        pmInp = new javax.swing.JComboBox<>();
        speInp = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableComment = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        daftarPekerjaan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        setUpFormats();
        amountInp = new javax.swing.JFormattedTextField(amountFormat);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Project Revision");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("PROJECT NUMBER");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("PROJECT NAME");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("PROJECT DATE");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("PROJECT MANAGER");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("PROJECT PIC");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("NOTES");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("COMMENT");

        pmInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmInpActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(204, 204, 204));
        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveButton.setText("AJUKAN");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        tableComment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Nama", "Komentar", "Respon"
            }
        ));
        jScrollPane1.setViewportView(tableComment);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("COMMENT HISTORY");

        daftarPekerjaan.setBackground(new java.awt.Color(204, 204, 204));
        daftarPekerjaan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        daftarPekerjaan.setText("DAFTAR PEKERJAAN");
        daftarPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarPekerjaanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("BUDGET");

        amountInp.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                amountInpInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(daftarPekerjaan)
                        .addGap(169, 169, 169)
                        .addComponent(saveButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(commentInp, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(noteInp, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(pDateInp, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(pNameInp, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(pNumberInp)
                                            .addComponent(pmInp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(amountInp)
                                            .addComponent(speInp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pNumberInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pNameInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(amountInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pDateInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pmInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(speInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(noteInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(commentInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(daftarPekerjaan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            save();
            returnToDaftarPekerjaan();
            JOptionPane.showMessageDialog(null, "Project Berhasil Disimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Project Gagal Disimpan, "+ e.getMessage());
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void pmInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmInpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmInpActionPerformed

    private void daftarPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarPekerjaanActionPerformed
        // TODO add your handling code here:
        returnToDaftarPekerjaan();
    }//GEN-LAST:event_daftarPekerjaanActionPerformed

    private void amountInpInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_amountInpInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_amountInpInputMethodTextChanged
    
    public void returnToDaftarPekerjaan(){
        DaftarPekerjaan daftarPekerjaan = new DaftarPekerjaan("Revisi");
        daftarPekerjaan.setLocationRelativeTo(null);
        daftarPekerjaan.setVisible(true); 
        dispose();
    }
    
    public void clear() {
        pNumberInp.setText("");
        pNameInp.setText("");
        amountInp.setText("0");
        pDateInp.setText("");
        noteInp.setText("");
        pmInp.setSelectedIndex(0);
        speInp.setSelectedIndex(0);
        commentInp.setText("");
    }
    
    public void save() throws SQLException {
        sql = "UPDATE prj_project_main set project_number = ?, project_name = ?, amount = ?, project_date = ?, notes = ?, pm_id = ?, pm_name = ?, spe_id = ?, spe_name = ?, status = ? WHERE id = ?";
        pstat = con.prepareStatement(sql);

        pstat.setString(1, pNumberInp.getText());
        pstat.setString(2, pNameInp.getText());
        pstat.setString(3, amountInp.getText());
        pstat.setString(4, pDateInp.getText());
        pstat.setString(5, noteInp.getText());
        pstat.setInt(6, pm.get(pmInp.getSelectedItem().toString()));
        pstat.setString(7, pmInp.getSelectedItem().toString());
        pstat.setInt(8, spe.get(speInp.getSelectedItem().toString()));
        pstat.setString(9, speInp.getSelectedItem().toString());
        pstat.setString(10, "Approval Budget");
        pstat.setInt(11, projectId);
        pstat.executeUpdate();

        sql = "INSERT INTO prj_project_comment(project_id, commenter_name, comment, response) VALUES (?, ?, ?, ?)";
        pstat = con.prepareStatement(sql);
                
        pstat.setInt(1, projectId);
        pstat.setString(2, name);
        pstat.setString(3, commentInp.getText());
        pstat.setString(4, "Revised");
        pstat.executeUpdate();
    }
    
    private void display() throws SQLException {
        while (tableComment.getRowCount() > 0) {
            ((javax.swing.table.DefaultTableModel) tableComment.getModel()).removeRow(0);
        }
        
        sql = "SELECT created_date, commenter_name, comment, response FROM prj_project_comment WHERE project_id = '"+projectId+"' ORDER BY id ASC;";
        rs = stat.executeQuery(sql);
        int columns = rs.getMetaData().getColumnCount();
        while (rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] = rs.getObject(i); // 1
            }
            ((javax.swing.table.DefaultTableModel) tableComment.getModel()).insertRow(rs.getRow() - 1,row);
        }
        
        
        sql = "SELECT * FROM prj_project_main WHERE id = '"+projectId+"' ORDER BY id ASC;";
        rs = stat.executeQuery(sql);
        while(rs.next()){
            pNumberInp.setText(rs.getString("project_number"));
            pNameInp.setText(rs.getString("project_name"));
            amountInp.setText(rs.getString("amount"));
            pDateInp.setText(rs.getString("project_date"));
            noteInp.setText(rs.getString("notes"));
            int size = pmInp.getItemCount();
            for (int i = 0; i < size; i++) {
                    
                if(pmInp.getItemAt(i).equals(rs.getString("pm_name"))){
                    pmInp.setSelectedIndex(i);
                }
            }
            size = speInp.getItemCount();
            for (int i = 0; i < size; i++) {
                    
                if(speInp.getItemAt(i).equals(rs.getString("spe_name"))){
                    speInp.setSelectedIndex(i);
                }
            }
        }
    }
    
    public void populateComboBox(){
        pm = getComboBoxData("SELECT emp.id, emp.name FROM ms_employee emp JOIN ms_role r ON emp.ms_role_id = r.id WHERE r.name = 'PIC' ORDER BY emp.name ASC");
        for(String s : pm.keySet()){
            pmInp.addItem(s);
        }
        
        spe = getComboBoxData("SELECT emp.id, emp.name FROM ms_employee emp JOIN ms_role r ON emp.ms_role_id = r.id WHERE r.name = 'Employee' ORDER BY emp.name ASC");
        for(String s : spe.keySet()){
            speInp.addItem(s);
        }
    }
    
    public HashMap<String, Integer> getComboBoxData(String query){
      HashMap<String, Integer> map = new HashMap<>();

       try {
           rs = stat.executeQuery(query);
           ComboBoxItem cmi;
           int i = 0;
           while(rs.next()){
               cmi = new ComboBoxItem(rs.getInt(1), rs.getString(2));
               map.put(cmi.getLabel(), cmi.getId());
           }

       } catch (SQLException ex) {

       }

       return map;
    }
    
    public int getId(String query){
        int id = 0;
        try {
           rs = stat.executeQuery(query);
           while(rs.next()){
               id = rs.getInt(1);
           }

       } catch (SQLException ex) {

       }
       return id;
    }
    
    private void setUpFormats() {
        amountFormat = NumberFormat.getNumberInstance();
    }
    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectRevision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectRevision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectRevision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectRevision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectRevision(projectId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField amountInp;
    private javax.swing.JTextField commentInp;
    private javax.swing.JButton daftarPekerjaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noteInp;
    private javax.swing.JTextField pDateInp;
    private javax.swing.JTextField pNameInp;
    private javax.swing.JTextField pNumberInp;
    private javax.swing.JComboBox<String> pmInp;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> speInp;
    private javax.swing.JTable tableComment;
    // End of variables declaration//GEN-END:variables

    //initialize SQL Connection  
    private Connection con;
    private Statement stat;
    private PreparedStatement pstat;
    private ResultSet rs;
    private String sql;
    private HashMap<String, Integer> pm;
    private HashMap<String, Integer> spe;
    
    final String name;
    final String nik;
    final String role;
    final String pos;
    
    final int projectId;
    //JPane
    private javax.swing.JOptionPane JOptionPane;
    private NumberFormat amountFormat;
}
