/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kkp.sipenalek.project;

import com.kkp.sipenalek.DBConnection;
import com.kkp.sipenalek.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Dell
 */
public class ProjectApproveBudget extends javax.swing.JFrame {

    /**
     * Creates new form ProjectCreate
     */
    public ProjectApproveBudget(int projectId) {
    	getContentPane().setBackground(new Color(255, 255, 255));

        this.name = UserSession.emp_name;
        this.nik = UserSession.nik;
        this.role = UserSession.role;
        this.pos = UserSession.pos;
        
        this.projectId = projectId;
        initComponents();
        
        setResizable(false);
        
        DBConnection DB = new DBConnection();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        try {
            display();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pNumberInp = new javax.swing.JTextField();
        pNameInp = new javax.swing.JTextField();
        pDateInp = new javax.swing.JTextField();
        noteInp = new javax.swing.JTextField();
        commentInp = new javax.swing.JTextField();
        daftarPekerjaan = new javax.swing.JButton();
        daftarPekerjaan.setForeground(new Color(255, 255, 255));
        saveButton = new javax.swing.JButton();
        saveButton.setForeground(new Color(255, 255, 255));
        revision = new javax.swing.JButton();
        revision.setForeground(new Color(255, 255, 255));
        jScrollPane1 = new javax.swing.JScrollPane();
        tableComment = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        pmInp = new javax.swing.JTextField();
        speInp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        amountInp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PERSETUJUAN ANGGARAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("NOMOR PROYEK");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NAMA PROYEK");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("TANGGAL PROYEK");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("MANAJER PROYEK");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("PENANGGUNG JAWAB");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CATATAN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("KOMENTAR");

        pNumberInp.setEditable(false);

        pNameInp.setEditable(false);

        pDateInp.setEditable(false);

        noteInp.setEditable(false);

        daftarPekerjaan.setBackground(new Color(80, 187, 0));
        daftarPekerjaan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        daftarPekerjaan.setText("DAFTAR PEKERJAAN");
        daftarPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarPekerjaanActionPerformed(evt);
            }
        });

        saveButton.setBackground(new Color(80, 187, 0));
        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveButton.setText("SETUJU");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        revision.setBackground(new Color(255, 10, 15));
        revision.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        revision.setText("REVISI");
        revision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisionActionPerformed(evt);
            }
        });

        tableComment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Nama", "Komentar", "Respon"
            }
        ));
        jScrollPane1.setViewportView(tableComment);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("RIWAYAT KOMENTAR");

        pmInp.setEditable(false);

        speInp.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("ANGGARAN");

        amountInp.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(28)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel10)
        						.addComponent(jLabel4)
        						.addComponent(jLabel5)
        						.addComponent(jLabel6)
        						.addComponent(jLabel7)
        						.addComponent(jLabel8)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jLabel3)
        									.addGap(90)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        										.addComponent(pNameInp, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        										.addComponent(pNumberInp)
        										.addComponent(amountInp, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        										.addComponent(pDateInp, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        										.addComponent(pmInp, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        										.addComponent(speInp, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        										.addComponent(noteInp, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        										.addComponent(commentInp, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE)))
        								.addComponent(jLabel2))
        							.addGap(0, 24, Short.MAX_VALUE))
        						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        							.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        								.addComponent(daftarPekerjaan)
        								.addPreferredGap(ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
        								.addComponent(revision)
        								.addPreferredGap(ComponentPlacement.UNRELATED)
        								.addComponent(saveButton))
        							.addComponent(jScrollPane1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(120)
        					.addComponent(jLabel1)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jLabel1)
        			.addGap(14)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(pNumberInp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(pNameInp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(5)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel10)
        				.addComponent(amountInp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(pDateInp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(pmInp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(speInp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(noteInp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(commentInp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(16)
        			.addComponent(jLabel9)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(daftarPekerjaan)
        				.addComponent(saveButton)
        				.addComponent(revision))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarPekerjaanActionPerformed
        // TODO add your handling code here:
        returnToDaftarPekerjaan();
    }//GEN-LAST:event_daftarPekerjaanActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            save();
            returnToDaftarPekerjaan();
            JOptionPane.showMessageDialog(null, "Approval Berhasil Disimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Approval Gagal Disimpan, "+ e.getMessage());
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void revisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisionActionPerformed
        // TODO add your handling code here:
        try {
            revision();
            returnToDaftarPekerjaan();
            JOptionPane.showMessageDialog(null, "Approval Berhasil Disimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Approval Gagal Disimpan, "+ e.getMessage());
        }
    }//GEN-LAST:event_revisionActionPerformed
    public void clear() {
        pNumberInp.setText("");
        pNameInp.setText("");
        amountInp.setText("0");
        pDateInp.setText("");
        noteInp.setText("");
        pmInp.setText("");
        speInp.setText("");
        commentInp.setText("");
    }
    
    public void returnToDaftarPekerjaan(){
        DaftarPekerjaan daftarPekerjaan = new DaftarPekerjaan("PERSETUJUAN ANGGARAN");
        daftarPekerjaan.setLocationRelativeTo(null);
        daftarPekerjaan.setVisible(true); 
        dispose();
    }
    
    public void save() throws SQLException {
        sql = "UPDATE prj_project_main set status = ? WHERE id = ?";
        pstat = con.prepareStatement(sql);

        pstat.setString(1, "Approval Project");
        pstat.setInt(2, projectId);
        pstat.executeUpdate();

        sql = "INSERT INTO prj_project_comment(project_id, commenter_name, comment, response) VALUES (?, ?, ?, ?)";
        pstat = con.prepareStatement(sql);
                
        pstat.setInt(1, projectId);
        pstat.setString(2, name);
        pstat.setString(3, commentInp.getText());
        pstat.setString(4, "Approved");
        pstat.executeUpdate();
    }
    
    public void revision() throws SQLException {
        sql = "UPDATE prj_project_main set status = ? WHERE id = ?";
        pstat = con.prepareStatement(sql);

        pstat.setString(1, "Revisi");
        pstat.setInt(2, projectId);
        pstat.executeUpdate();

        sql = "INSERT INTO prj_project_comment(project_id, commenter_name, comment, response) VALUES (?, ?, ?, ?)";
        pstat = con.prepareStatement(sql);
                
        pstat.setInt(1, projectId);
        pstat.setString(2, name);
        pstat.setString(3, commentInp.getText());
        pstat.setString(4, "Revisi");
        pstat.executeUpdate();
    }
      
    private void display() throws SQLException {
        while (tableComment.getRowCount() > 0) {
            ((javax.swing.table.DefaultTableModel) tableComment.getModel()).removeRow(0);
        }
        
        sql = "SELECT created_date, commenter_name, comment, response FROM prj_project_comment WHERE project_id = '"+projectId+"' ORDER BY id ASC;";
        rs = stat.executeQuery(sql);
        int columns = rs.getMetaData().getColumnCount();
        while (rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] = rs.getObject(i); // 1
            }
            ((javax.swing.table.DefaultTableModel) tableComment.getModel()).insertRow(rs.getRow() - 1,row);
        }
        
        
        sql = "SELECT * FROM prj_project_main WHERE id = '"+projectId+"' ORDER BY id ASC;";
        rs = stat.executeQuery(sql);
        while(rs.next()){
            pNumberInp.setText(rs.getString("project_number"));
            pNameInp.setText(rs.getString("project_name"));
            amountInp.setText(rs.getString("amount"));
            pDateInp.setText(rs.getString("project_date"));
            noteInp.setText(rs.getString("notes"));
            pmInp.setText(rs.getString("pm_name"));
            speInp.setText(rs.getString("spe_name"));
        }
    }
 
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectApproveBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectApproveBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectApproveBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectApproveBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectApproveBudget(projectId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountInp;
    private javax.swing.JTextField commentInp;
    private javax.swing.JButton daftarPekerjaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noteInp;
    private javax.swing.JTextField pDateInp;
    private javax.swing.JTextField pNameInp;
    private javax.swing.JTextField pNumberInp;
    private javax.swing.JTextField pmInp;
    private javax.swing.JButton revision;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField speInp;
    private javax.swing.JTable tableComment;
    // End of variables declaration//GEN-END:variables

    //initialize SQL Connection  
    private Connection con;
    private Statement stat;
    private PreparedStatement pstat;
    private ResultSet rs;
    private String sql;
    final String name;
    final String nik;
    final String role;
    final String pos;
    
    final int projectId;
    //JPane
    private javax.swing.JOptionPane JOptionPane;
}
